tweak script

diff --git a/arch-ppa b/arch-ppa
--- a/arch-ppa
+++ b/arch-ppa
@@ -137,7 +137,7 @@ add() {
 update() {
     # Update a package and it's dependencies from the AUR
     (
-	#set -e
+	#set -e # breaks updating all if one fails, ignore errors
 	if [ "$#" -eq 0 ]; then
 	    cd $basedir/src
 	    update *
@@ -259,12 +259,15 @@ build() {
 }
 
 rebuild() {
+		(
+		set -e
 		setup
 		repo_name=$1
 		mkdir -p $basedir/$repo_name
 		shift
 		arch-nspawn $chroot/$repo_name pacman -Rscn --noconfirm "$@"
 		build "$repo_name" "$@"
+		)
 }
 
 if [ "$#" -gt 0 ]; then
