update displaylink+evdi

diff --git a/src/displaylink/PKGBUILD b/src/displaylink/PKGBUILD
--- a/src/displaylink/PKGBUILD
+++ b/src/displaylink/PKGBUILD
@@ -1,30 +1,36 @@
 # Maintainer: rHermes <teodor_spaeren@riseup.net>
+# Maintainer: bnavigator <code@bnavigator.de>
 # Contributor: PlusMinus
 # Contributor: rhabbachi
 
 pkgname=displaylink
-pkgver=5.2.14
+pkgver=5.4.1
+_releasedate=2021-09
+_pkgfullver=5.4.1-55.174
 pkgrel=1
 pkgdesc="Linux driver for DL-6xxx, DL-5xxx, DL-41xx and DL-3x00"
-arch=('i686' 'x86_64')
-url="http://www.displaylink.com/downloads/ubuntu.php"
+arch=('i686' 'x86_64' 'arm' 'armv6h' 'armv7h' 'aarch64')
+url=""
 license=('custom' 'GPL2' 'LGPL2.1')
-depends=('evdi>=1.5.0' 'libusb>=1.0.0')
+depends=('evdi>=1.9.1'
+         'libusb>=1.0.0')
 makedepends=('grep' 'gawk' 'wget')
 install=
-changelog="release-note.txt"
-source=(displaylink-driver-$pkgver.zip::https://www.displaylink.com/downloads/file?id=1369
-	udev.sh
+changelog="displaylink-release-notes-${pkgver}.txt"
+source=(displaylink-driver-${pkgver}.zip::https://www.synaptics.com/sites/default/files/exe_files/${_releasedate}/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu${pkgver}-EXE.zip
+        displaylink-release-notes-${pkgver}.txt::https://www.synaptics.com/sites/default/files/release_notes/${_releasedate}/DisplayLink%20USB%20Graphics%20Software%20for%20Ubuntu${pkgver}-Release%20Notes.txt
+        DISPLAYLINK-EULA
+        udev.sh
         99-displaylink.rules 
 	displaylink.service 
         displaylink-sleep.sh)
-md5sums=('a96ae6fc0d244ec4f9a8e9482f6c1535'
-         'd5de775e41af06edbd8073adc490139d'
-         '20495d81c7d2540910ef86dc437b7fac'
-         'c141a15e973481c7d961f8e135627ca4'
-         '7cbd9ab2ac79ba66e8297689c6e5483e')
-
-DLAGENTS=('https::/usr/bin/wget -O %o --post-data=fileId=1369&accept_submit=Accept %u')
+sha256sums=('0cc71807122d7bcafab422d7b4bd707018a2f28005bce4fae9f585f4e5e63aae'
+            '895a2100cdebf217f43873761554cd179e9eaa498649c9eb68f1f007797fbf83'
+            '2f81fea43332a62b2cf1dd47e56ea01caf1e886bcd16c3f82b18bfe148fb21a9'
+            'dc41ae8a2c287fc50fdda65bad8b0ffd76726f7773c25e1b0c5b7de95cecbdb6'
+            'c08a4726cf4e2f92c7cab00168ae9cc8d69d36a67c570609396a4a674934245a'
+            '342e83abfe2a38d5635ea928345e933d2ad127ebd3f7caca476663d4f583684b'
+            '8be4ab7616e38f91746bdd3e7fafe9004322a8be8e6722389746df9868d576e0')
 
 # Update with > updpkgsums
 
@@ -42,33 +48,35 @@ package() {
   install -d -m755 "$pkgdir/var/log/displaylink"
 
   echo "Extracting DisplayLink Driver Package"
-  cd $srcdir
-  chmod +x displaylink-driver-$pkgver.run
-  ./displaylink-driver-$pkgver.run --target $pkgname-$pkgver --noexec
-  cd "$pkgname-$pkgver"
+  pushd $srcdir
+  chmod +x displaylink-driver-${_pkgfullver}.run
+  ./displaylink-driver-${_pkgfullver}.run \
+     --noexec \
+     --target $pkgname-$pkgver \
+     --nox11 \
+     --noprogress
+  test -d $pkgname-$pkgver || (echo "Extracting the driver with the .run installer failed"; exit 1)
+  pushd $pkgname-$pkgver
   
-  if [ "$CARCH" == "i686" ]; then
-    ARCH="x86"
-  elif [ "$CARCH" == "x86_64" ]; then
-    ARCH="x64"
-  fi
-
-  ARCH+="-ubuntu-1604"
+  case $CARCH in
+    i686)
+      ARCH="x86-ubuntu-1604" ;;
+    x86_64)
+      ARCH="x64-ubuntu-1604" ;;
+    arm|armv6h|armv7h|aarch64)
+      ARCH="arm-linux-gnueabihf" ;;
+  esac
   
   echo "Installing DisplayLink Manager $ARCH"
   install -D -m755 $ARCH/DisplayLinkManager $COREDIR/DisplayLinkManager
 
-  # I wonder if this is even necessary but I'm too lazy to find out
-  echo "Creating symlinks for evdi and libusb"
-  ln -s $(ldconfig -p | grep libevdi | awk 'NR==1{print $4}') $COREDIR/libevdi.so
-
-  ln -s $(ldconfig -p | grep libusb- | awk 'NR==1{print $4}') $COREDIR/libusb-1.0.so.0.1.0
-  ln -s $(ldconfig -p | grep libusb- | awk 'NR==1{print $4}') $COREDIR/libusb-1.0.so.0
-  ln -s $(ldconfig -p | grep libusb- | awk 'NR==1{print $4}') $COREDIR/libusb-1.0.so
-  
   echo "Installing firmware packages"
   install -D -m644 *.spkg $COREDIR
 
   echo "Installing license file"
   install -D -m644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
+  popd
+  popd
+  install -D -m644 DISPLAYLINK-EULA "${pkgdir}/usr/share/licenses/${pkgname}/DISPLAYLINK-EULA"
+
 }
